### ISSUE TITLE
Normalized l2-dissimilarity

### ISSUE THREAD

**Issue by ScottLiao920** [softsys4ai/athena#35]
Hi I'm trying to reproduce your experiment but while I was trying to evaluate FGSM attacks under white box settings, I found that the normalized l2-dissimilarity for a FGSM at eps=0.1 is only about 0.007. As in your code, the upper bound for an white-box attack is determined by some pre-generated adversarial examples. I'm wondering how you guys finish the experiments as in Fig. 7 in your paper?

**Comment by MENG2010** [comment]
Hi Scott,

Thanks for having an interest in our work. 

Our approach is an ensemble model that was built upon many weak defenses (WD), it first collects predictions from all WDs then finds the final label for given input using some strategy. In the context of whitebox threat model, the attacker knows everything regarding the model (Section IV.C) and wants to generate adversarial examples (AE) that fool as many WDs as possible, one possible approach is by introducing adversarial perturbations based on various WDs into one AE. 

To do so, we use a greedy approach to add perturbations based on multiple WDs into one AE (Algorithm 1). This algorithm has two constraints *N* (the number of WDs based on which we generate the adversarial perturbations, for a whitebox threat model of a Majority-Voting ensemble, $N=#\_of\_WDs \times 0.9$.) and *max\_dissimilarity* (the maximum l2-dissimilarity of each generated AE, in our study, we ).

**Comment by ScottLiao920** [comment]
Hi Meng, 

Thanks for reply. As indicated in your code (/src/evaluation/eval_whitebox.py, line 291), it seems that the max_dissimilarity is set as the normalized l2 norm between benign samples and adversarial examples generated by FGSM attack at eps=0.1. According to my experiement, the normalized frobenius norm of them should be as small as 0.01. Just wonder do i need to adjust the max_perturb argument in line 291 as 0.1~1.0 during experiments?

Thanks

**Comment by MENG2010** [comment]
For each set of AE, it is a value passed via parameter max_dissimilarity.

**Comment by ScottLiao920** [comment]
Oh understood. Thanks!
